version: '3.9'
services:
    nginx:
        build:
            context: bin/nginx
        container_name: ${CONTAINER_NAME}docker_server_nginx
        ports:
            - ${PORT_APACHE}:80
        volumes:
#            - ./home/dan/Docker-Jenkins/data/jenkins_home/workspace:/usr/share/nginx/html
            - ./www/${PROJECT}:/usr/share/nginx/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always
    php:
        build:
            context: bin/php
        container_name: ${CONTAINER_NAME}docker_php_nginx
        volumes:
#            - ./home/dan/Docker-Jenkins/data/jenkins_home/workspace:/usr/share/nginx/html
            - ./www/${PROJECT}:/usr/share/nginx/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        restart: always
    redis:
        build:
            context: bin/redis
        container_name: ${CONTAINER_NAME}docker_redis_nginx
        depends_on:
            -  php
        restart: always
    mysql:
        build:
            context: bin/mysql
        container_name: ${CONTAINER_NAME}docker_mysql_nginx
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${PORT_MYSQL}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        restart: always